name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode.app
          xcodebuild -version
          xcrun simctl list devices

      - name: Build project
        run: |
          xcodebuild clean build \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -derivedDataPath DerivedData

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -only-testing:QaseAPIProjTests \
            -resultBundlePath TestResults/UnitTests.xcresult \
            | tee test.log || echo "Unit tests failed - check logs"
        continue-on-error: true

      - name: Run UI Tests
        run: |
          xcodebuild test \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -only-testing:QaseAPIProjUITests \
            -resultBundlePath TestResults/UITests.xcresult \
            | tee uitest.log || echo "UI tests failed - check logs"
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            TestResults/*.xcresult
            *.log
