name: QaseAPIProj CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: |
          sudo xcode-select -switch /Applications/Xcode.app
          xcodebuild -version

      - name: Show available devices
        run: xcrun simctl list devices

      - name: Build project
        run: |
          xcodebuild build \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -quiet

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -enableCodeCoverage YES \
            -only-testing:QaseAPIProjTests \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run UI Tests
        run: |
          xcodebuild test \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -enableCodeCoverage YES \
            -only-testing:QaseAPIProjUITests \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload code coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: |
            */**/Coverage.profdata
            */**/Coverage.json
