name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build
        run: xcodebuild clean build -project QaseAPIProj.xcodeproj -scheme QaseAPIProj -destination 'platform=iOS Simulator,name=iPhone 16'

      - name: Run tests
        run: xcodebuild test -project QaseAPIProj.xcodeproj -scheme QaseAPIProjTests -destination 'platform=iOS Simulator,name=iPhone 16'

      - name: Run UI tests
        run: xcodebuild test -project QaseAPIProj.xcodeproj -scheme QaseAPIProjUITests -destination 'platform=iOS Simulator,name=iPhone 16'
