name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-15
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode environment
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.3.app
          xcodebuild -version
          xcrun simctl list devices
          
      - name: Create test directories
        run: |
          mkdir -p TestResults
          mkdir -p Logs

      - name: Build project
        run: |
          xcodebuild clean build \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath DerivedData \
            | tee Logs/build.log || echo "Build failed - check logs"
        continue-on-error: true

      - name: Run Unit Tests
        run: |
          mkdir -p TestResults/UnitTests
          xcodebuild test \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -only-testing:QaseAPIProjTests \
            -resultBundlePath TestResults/UnitTests/UnitTests.xcresult \
            -derivedDataPath DerivedData \
            | tee Logs/unit-tests.log || echo "Unit tests failed - check logs"
        continue-on-error: true

      - name: Run UI Tests
        run: |
          mkdir -p TestResults/UITests
          xcodebuild test \
            -project QaseAPIProj.xcodeproj \
            -scheme QaseAPIProj \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -only-testing:QaseAPIProjUITests \
            -resultBundlePath TestResults/UITests/UITests.xcresult \
            -derivedDataPath DerivedData \
            | tee Logs/ui-tests.log || echo "UI tests failed - check logs"
        continue-on-error: true

      - name: Prepare artifacts
        if: always()
        run: |
          # Копируем логи тестов
          cp Logs/*.log TestResults/
          
          # Проверяем существование файлов
          echo "Contents of TestResults:"
          ls -la TestResults/*
          echo "Contents of Logs:"
          ls -la Logs/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            TestResults/
            Logs/
